import { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Men's Legal Attire",
    slug: "mens-legal-attire",
    description: "Premium tailored suits and gowns for men",
    image_url: "/product-image/demo.webp",
    parent_id: null,
  },
  {
    id: "cat-2",
    name: "Women's Legal Attire",
    slug: "womens-legal-attire",
    description: "Distinguished legal gowns and coats for women",
    image_url: "/product-image/demo.webp",
    parent_id: null,
  },
  {
    id: "cat-6",
    name: "Accessories",
    slug: "accessories",
    description: "Essential legal accessories: ties, bands, belts, and more",
    image_url: "/product-image/demo.webp",
    parent_id: null,
  },
  {
    id: "cat-7",
    name: "Package Deals",
    slug: "combos",
    description: "Curated bundles for the legal professional",
    image_url: "/product-image/demo.webp",
    parent_id: null,
  },
];

export const products: Product[] = [
  {
    id: "TDO-CT-BLK",
    name: "Dress Coat",
    slug: "dress-coat",
    sku: "TDO-CT-BLK",
    description: "Premium Advocate Dress Coat crafted for a sharp and professional courtroom look.",
    category_id: "cat-1",
    base_price: 2500,
    compare_at_price: 3000,
    fabric: "Polyviscose",
    fit: "modern",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-1", product_id: "TDO-CT-BLK", url: "/product-image/TDO-CT-BLK.png", alt: "Dress Coat", position: 0, is_primary: true }],
    variants: [{ id: "var-1", product_id: "TDO-CT-BLK", sku: "TDO-CT-BLK", size: "Standard", stock_quantity: 100, price: 2500, compare_at_price: 3000, is_out_of_stock: false }],
  },
  {
    id: "TDO-WC-BLK",
    name: "Dress Waistcoat",
    slug: "dress-waistcoat",
    sku: "TDO-WC-BLK",
    description: "Premium Dress Waistcoat (Half Jacket) designed for a sharp and elegant formal look.",
    category_id: "cat-1",
    base_price: 1400,
    compare_at_price: 1800,
    fabric: "Polyviscose",
    fit: "modern",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-2", product_id: "TDO-WC-BLK", url: "/product-image/TDO-WC-BLK.png", alt: "Dress Waistcoat", position: 0, is_primary: true }],
    variants: [{ id: "var-2", product_id: "TDO-WC-BLK", sku: "TDO-WC-BLK", size: "Standard", stock_quantity: 100, price: 1400, compare_at_price: 1800, is_out_of_stock: false }],
  },
  {
    id: "TDO-PC-RAY",
    name: "Pant Cloth",
    slug: "pant-cloth-raymond",
    sku: "TDO-PC-RAY",
    description: "Premium Raymond pant cloth offering superior quality fabric for tailored trousers.",
    category_id: "cat-1",
    base_price: 1200,
    compare_at_price: 1500,
    fabric: "Raymond Fabric",
    fit: "classic",
    color: "Grey/Black",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-3", product_id: "TDO-PC-RAY", url: "/product-image/TDO-PC-RAY.png", alt: "Pant Cloth", position: 0, is_primary: true }],
    variants: [{ id: "var-3", product_id: "TDO-PC-RAY", sku: "TDO-PC-RAY", size: "Standard", stock_quantity: 100, price: 1200, compare_at_price: 1500, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-SH-WHT",
    name: "White Dress Shirt",
    slug: "white-dress-shirt",
    sku: "TDO-GW-SH-WHT",
    description: "Classic white dress shirt designed for a crisp and professional appearance.",
    category_id: "cat-1",
    base_price: 700,
    compare_at_price: 900,
    fabric: "Cotton Blend",
    fit: "slim",
    color: "White",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-4", product_id: "TDO-GW-SH-WHT", url: "/product-image/TDO-GW-SH-WHT.png", alt: "White Dress Shirt", position: 0, is_primary: true }],
    variants: [{ id: "var-4", product_id: "TDO-GW-SH-WHT", sku: "TDO-GW-SH-WHT", size: "Standard", stock_quantity: 100, price: 700, compare_at_price: 900, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-BLK-BUR",
    name: "Advocate Gown - Burkha",
    slug: "gown-burkha",
    sku: "TDO-GW-BLK-BUR",
    description: "Premium advocate gown crafted in Burkha fabric for durability and comfort.",
    category_id: "cat-1",
    base_price: 1800,
    compare_at_price: 2200,
    fabric: "Burkha Fabric",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: false,
    category: categories[0],
    images: [{ id: "img-5", product_id: "TDO-GW-BLK-BUR", url: "/product-image/TDO-GW-BLK-BUR.png", alt: "Advocate Gown - Burkha", position: 0, is_primary: true }],
    variants: [{ id: "var-5", product_id: "TDO-GW-BLK-BUR", sku: "TDO-GW-BLK-BUR", size: "Standard", stock_quantity: 100, price: 1800, compare_at_price: 2200, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-BLK-SUN",
    name: "Advocate Gown - Sunsilk",
    slug: "gown-sunsilk",
    sku: "TDO-GW-BLK-SUN",
    description: "Lightweight and smooth Sunsilk fabric gown offering comfort and refined appearance.",
    category_id: "cat-1",
    base_price: 2000,
    compare_at_price: 2400,
    fabric: "Sunsilk Fabric",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: false,
    category: categories[0],
    images: [{ id: "img-6", product_id: "TDO-GW-BLK-SUN", url: "/product-image/TDO-GW-BLK-SUN.png", alt: "Advocate Gown - Sunsilk", position: 0, is_primary: true }],
    variants: [{ id: "var-6", product_id: "TDO-GW-BLK-SUN", sku: "TDO-GW-BLK-SUN", size: "Standard", stock_quantity: 100, price: 2000, compare_at_price: 2400, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-BLK-TCT",
    name: "Advocate Gown - T-Cot",
    slug: "gown-tcot",
    sku: "TDO-GW-BLK-TCT",
    description: "Durable T-Cot fabric gown combining comfort and longevity.",
    category_id: "cat-1",
    base_price: 2000,
    compare_at_price: 2400,
    fabric: "T-Cot Fabric",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: false,
    category: categories[0],
    images: [{ id: "img-7", product_id: "TDO-GW-BLK-TCT", url: "/product-image/TDO-GW-BLK-TCT.png", alt: "Advocate Gown - T-Cot", position: 0, is_primary: true }],
    variants: [{ id: "var-7", product_id: "TDO-GW-BLK-TCT", sku: "TDO-GW-BLK-TCT", size: "Standard", stock_quantity: 100, price: 2000, compare_at_price: 2400, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-BLK-RAY",
    name: "Advocate Gown - Raymond",
    slug: "gown-raymond",
    sku: "TDO-GW-BLK-RAY",
    description: "Premium Raymond fabric gown known for superior quality and finish.",
    category_id: "cat-1",
    base_price: 4500,
    compare_at_price: 5200,
    fabric: "Raymond Fabric",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-8", product_id: "TDO-GW-BLK-RAY", url: "/product-image/TDO-GW-BLK-RAY.png", alt: "Advocate Gown - Raymond", position: 0, is_primary: true }],
    variants: [{ id: "var-8", product_id: "TDO-GW-BLK-RAY", sku: "TDO-GW-BLK-RAY", size: "Standard", stock_quantity: 100, price: 4500, compare_at_price: 5200, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-BLK-LAC",
    name: "Advocate Gown - Lachka",
    slug: "gown-lachka",
    sku: "TDO-GW-BLK-LAC",
    description: "Premium Lachka fabric gown with superior drape and elegant texture.",
    category_id: "cat-1",
    base_price: 7500,
    compare_at_price: 8500,
    fabric: "Lachka Fabric",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[0],
    images: [{ id: "img-9", product_id: "TDO-GW-BLK-LAC", url: "/product-image/TDO-GW-BLK-LAC.png", alt: "Advocate Gown - Lachka", position: 0, is_primary: true }],
    variants: [{ id: "var-9", product_id: "TDO-GW-BLK-LAC", sku: "TDO-GW-BLK-LAC", size: "Standard", stock_quantity: 100, price: 7500, compare_at_price: 8500, is_out_of_stock: false }],
  },
  {
    id: "TDO-GW-WC-BLK",
    name: "Women's Dress Coat",
    slug: "womens-dress-coat",
    sku: "TDO-GW-WC-BLK",
    description: "Premium women's advocate coat tailored for a sharp and elegant courtroom appearance.",
    category_id: "cat-2",
    base_price: 2500,
    compare_at_price: 3000,
    fabric: "Polyviscose",
    fit: "modern",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[1],
    images: [{ id: "img-10", product_id: "TDO-GW-WC-BLK", url: "/product-image/TDO-GW-WC-BLK.jpeg", alt: "Women's Dress Coat", position: 0, is_primary: true }],
    variants: [{ id: "var-10", product_id: "TDO-GW-WC-BLK", sku: "TDO-GW-WC-BLK", size: "Standard", stock_quantity: 100, price: 2500, compare_at_price: 3000, is_out_of_stock: false }],
  },
  {
    id: "TDO-ACC-TIE",
    name: "Black Tie",
    slug: "black-tie",
    sku: "TDO-ACC-TIE",
    description: "Classic black formal tie crafted with a smooth satin finish.",
    category_id: "cat-6",
    base_price: 120,
    compare_at_price: 150,
    fabric: "Polyester",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[2],
    images: [{ id: "img-11", product_id: "TDO-ACC-TIE", url: "/product-image/TDO-ACC-TIE.png", alt: "Black Tie", position: 0, is_primary: true }],
    variants: [{ id: "var-11", product_id: "TDO-ACC-TIE", sku: "TDO-ACC-TIE", size: "Standard", stock_quantity: 100, price: 120, compare_at_price: 150, is_out_of_stock: false }],
  },
  {
    id: "TDO-ACC-BLT",
    name: "Leather Belt",
    slug: "leather-belt",
    sku: "TDO-ACC-BLT",
    description: "Premium genuine leather belt with a durable metal buckle.",
    category_id: "cat-6",
    base_price: 400,
    compare_at_price: 500,
    fabric: "Genuine Leather",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[2],
    images: [{ id: "img-12", product_id: "TDO-ACC-BLT", url: "/product-image/TDO-ACC-BLT.png", alt: "Leather Belt", position: 0, is_primary: true }],
    variants: [{ id: "var-12", product_id: "TDO-ACC-BLT", sku: "TDO-ACC-BLT", size: "Standard", stock_quantity: 100, price: 400, compare_at_price: 500, is_out_of_stock: false }],
  },
  {
    id: "TDO-PKG-CO-PN",
    name: "Coat & Pant Set (2-Piece)",
    slug: "coat-pant-set-2-piece",
    sku: "TDO-PKG-CO-PN",
    description: "Elegant 2-piece package including premium advocate coat and matching pant.",
    category_id: "cat-7",
    base_price: 3800,
    compare_at_price: 4200,
    fabric: "Polyviscose / Raymond",
    fit: "modern",
    color: "Black",
    is_visible: true,
    is_featured: true,
    category: categories[3],
    images: [{ id: "img-13", product_id: "TDO-PKG-CO-PN", url: "/product-image/TDO-PKG-CO-PN.jpg", alt: "Coat & Pant Set", position: 0, is_primary: true }],
    variants: [{ id: "var-13", product_id: "TDO-PKG-CO-PN", sku: "TDO-PKG-CO-PN", size: "Standard", stock_quantity: 100, price: 3800, compare_at_price: 4200, is_out_of_stock: false }],
  },
];
