import { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Coats / Jackets",
    slug: "coats-jackets",
    description: "Tailored advocate coats and jackets",
    image_url: "/advocate_dress_coat.jpeg",
    parent_id: null,
  },
  {
    id: "cat-2",
    name: "Gown / Robe",
    slug: "gown-robe",
    description: "Distinguished legal gowns and robes",
    image_url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
    parent_id: null,
  },
  {
    id: "cat-3",
    name: "Pant",
    slug: "pant",
    description: "Professional formal trousers",
    image_url: "/hunters-race-MYbhN8KaaEc-unsplash.jpg",
    parent_id: null,
  },
  {
    id: "cat-4",
    name: "Shirts",
    slug: "shirts",
    description: "Crisp white and formal shirts",
    image_url: "/pexels-unique-bash-creative-1927464998-34850161.jpg",
    parent_id: null,
  },
  {
    id: "cat-5",
    name: "Vest",
    slug: "vest",
    description: "Formal waistcoats and vests",
    image_url: "/pexels-pavel-danilyuk-8112126.jpg",
    parent_id: null,
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "The Barrister's Charcoal Three-Piece",
    slug: "barristers-charcoal-three-piece",
    description:
      "A refined three-piece suit crafted from Super 120s Italian wool. Perfect for courtroom appearances and boardroom meetings. Features a half-canvas construction for superior drape and durability.",
    category_id: "cat-1",
    base_price: 45000,
    compare_at_price: 55000,
    cost_per_item: 18000,
    fabric: "Super 120s Italian Wool",
    fit: "slim",
    color: "Charcoal",
    is_visible: true,
    is_featured: true,
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
    deleted_at: null,
    category: categories[0],
    images: [
      {
        id: "img-1-1",
        product_id: "prod-1",
        url: "/hunters-race-MYbhN8KaaEc-unsplash.jpg",
        thumbnail_url: "/hunters-race-MYbhN8KaaEc-unsplash.jpg",
        medium_url: "/hunters-race-MYbhN8KaaEc-unsplash.jpg",
        alt: "Charcoal three-piece suit front view",
        position: 0,
        is_primary: true,
      },
      {
        id: "img-1-2",
        product_id: "prod-1",
        url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        thumbnail_url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        medium_url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        alt: "Charcoal three-piece suit back view",
        position: 1,
        is_primary: false,
      },
    ],
    variants: [
      { id: "var-1-1", product_id: "prod-1", sku: "BAR-CH-38", size: "38R", stock_quantity: 5, price: 45000, compare_at_price: 55000, is_out_of_stock: false },
      { id: "var-1-2", product_id: "prod-1", sku: "BAR-CH-40", size: "40R", stock_quantity: 8, price: 45000, compare_at_price: 55000, is_out_of_stock: false },
      { id: "var-1-3", product_id: "prod-1", sku: "BAR-CH-42", size: "42R", stock_quantity: 3, price: 45000, compare_at_price: 55000, is_out_of_stock: false },
      { id: "var-1-4", product_id: "prod-1", sku: "BAR-CH-44", size: "44R", stock_quantity: 0, price: 45000, compare_at_price: 55000, is_out_of_stock: true },
    ],
  },
  {
    id: "prod-2",
    name: "The Solicitor's Navy Two-Piece",
    slug: "solicitors-navy-two-piece",
    description:
      "A timeless navy two-piece suit made from Merino wool blend. Features a modern fit with clean lines and a soft shoulder. Ideal for daily professional wear.",
    category_id: "cat-1",
    base_price: 35000,
    compare_at_price: null,
    cost_per_item: 14000,
    fabric: "Merino Wool Blend",
    fit: "modern",
    color: "Navy",
    is_visible: true,
    is_featured: true,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
    deleted_at: null,
    category: categories[0],
    images: [
      {
        id: "img-2-1",
        product_id: "prod-2",
        url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        thumbnail_url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        medium_url: "/nussbaum-law-IOvsEAEjnDE-unsplash.jpg",
        alt: "Navy two-piece suit",
        position: 0,
        is_primary: true,
      },
      {
        id: "img-2-2",
        product_id: "prod-2",
        url: "/pexels-pavel-danilyuk-8112126.jpg",
        thumbnail_url: "/pexels-pavel-danilyuk-8112126.jpg",
        medium_url: "/pexels-pavel-danilyuk-8112126.jpg",
        alt: "Navy two-piece suit detail",
        position: 1,
        is_primary: false,
      },
    ],
    variants: [
      { id: "var-2-1", product_id: "prod-2", sku: "SOL-NV-38", size: "38R", stock_quantity: 10, price: 35000, compare_at_price: null, is_out_of_stock: false },
      { id: "var-2-2", product_id: "prod-2", sku: "SOL-NV-40", size: "40R", stock_quantity: 12, price: 35000, compare_at_price: null, is_out_of_stock: false },
      { id: "var-2-3", product_id: "prod-2", sku: "SOL-NV-42", size: "42R", stock_quantity: 6, price: 35000, compare_at_price: null, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-3",
    name: "The Advocate's Black Tuxedo",
    slug: "advocates-black-tuxedo",
    description:
      "An elegant black tuxedo with satin lapels for formal galas and award ceremonies. Made from premium Super 130s wool. Features a classic fit with a single-button closure.",
    category_id: "cat-1",
    base_price: 65000,
    compare_at_price: 75000,
    cost_per_item: 28000,
    fabric: "Super 130s Wool",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: true,
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
    deleted_at: null,
    category: categories[0],
    images: [
      {
        id: "img-3-1",
        product_id: "prod-3",
        url: "/pexels-ekaterina-bolovtsova-6077961.jpg",
        thumbnail_url: "/pexels-ekaterina-bolovtsova-6077961.jpg",
        medium_url: "/pexels-ekaterina-bolovtsova-6077961.jpg",
        alt: "Black tuxedo",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-3-1", product_id: "prod-3", sku: "ADV-BK-38", size: "38R", stock_quantity: 3, price: 65000, compare_at_price: 75000, is_out_of_stock: false },
      { id: "var-3-2", product_id: "prod-3", sku: "ADV-BK-40", size: "40R", stock_quantity: 5, price: 65000, compare_at_price: 75000, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-4",
    name: "The Silk Navy Tie",
    slug: "silk-navy-tie",
    description:
      "A premium silk tie in deep navy with subtle diagonal stripes. Handcrafted from 100% mulberry silk. Width: 8cm. Made in Italy.",
    category_id: "cat-3",
    base_price: 3500,
    compare_at_price: 4500,
    cost_per_item: 800,
    fabric: "100% Mulberry Silk",
    fit: "classic",
    color: "Navy",
    is_visible: true,
    is_featured: false,
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
    deleted_at: null,
    category: categories[2],
    images: [
      {
        id: "img-4-1",
        product_id: "prod-4",
        url: "/pexels-karola-g-7876289.jpg",
        thumbnail_url: "/pexels-karola-g-7876289.jpg",
        medium_url: "/pexels-karola-g-7876289.jpg",
        alt: "Silk navy tie",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-4-1", product_id: "prod-4", sku: "TIE-NV-STD", size: "Standard", stock_quantity: 25, price: 3500, compare_at_price: 4500, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-5",
    name: "The Queen's Counsel Cream Shirt",
    slug: "queens-counsel-cream-shirt",
    description:
      "A luxurious Egyptian cotton dress shirt in cream. Features a semi-spread collar and French cuffs. Perfect for pairing with dark suits.",
    category_id: "cat-2",
    base_price: 8500,
    compare_at_price: null,
    cost_per_item: 2500,
    fabric: "Egyptian Cotton",
    fit: "slim",
    color: "Cream",
    is_visible: true,
    is_featured: false,
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
    deleted_at: null,
    category: categories[1],
    images: [
      {
        id: "img-5-1",
        product_id: "prod-5",
        url: "/pexels-unique-bash-creative-1927464998-34850161.jpg",
        thumbnail_url: "/pexels-unique-bash-creative-1927464998-34850161.jpg",
        medium_url: "/pexels-unique-bash-creative-1927464998-34850161.jpg",
        alt: "Cream dress shirt",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-5-1", product_id: "prod-5", sku: "QCC-CR-S", size: "S", stock_quantity: 8, price: 8500, compare_at_price: null, is_out_of_stock: false },
      { id: "var-5-2", product_id: "prod-5", sku: "QCC-CR-M", size: "M", stock_quantity: 15, price: 8500, compare_at_price: null, is_out_of_stock: false },
      { id: "var-5-3", product_id: "prod-5", sku: "QCC-CR-L", size: "L", stock_quantity: 10, price: 8500, compare_at_price: null, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-6",
    name: "The Judge's Burgundy Three-Piece",
    slug: "judges-burgundy-three-piece",
    description:
      "A distinguished burgundy three-piece suit for those who command attention. Crafted from Italian Super 140s wool with a subtle sheen.",
    category_id: "cat-1",
    base_price: 55000,
    compare_at_price: 65000,
    cost_per_item: 22000,
    fabric: "Super 140s Italian Wool",
    fit: "modern",
    color: "Burgundy",
    is_visible: true,
    is_featured: true,
    created_at: "2024-01-25T00:00:00Z",
    updated_at: "2024-01-25T00:00:00Z",
    deleted_at: null,
    category: categories[0],
    images: [
      {
        id: "img-6-1",
        product_id: "prod-6",
        url: "/pexels-pavel-danilyuk-8112126.jpg",
        thumbnail_url: "/pexels-pavel-danilyuk-8112126.jpg",
        medium_url: "/pexels-pavel-danilyuk-8112126.jpg",
        alt: "Burgundy three-piece suit",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-6-1", product_id: "prod-6", sku: "JBG-BG-38", size: "38R", stock_quantity: 4, price: 55000, compare_at_price: 65000, is_out_of_stock: false },
      { id: "var-6-2", product_id: "prod-6", sku: "JBG-BG-40", size: "40R", stock_quantity: 7, price: 55000, compare_at_price: 65000, is_out_of_stock: false },
      { id: "var-6-3", product_id: "prod-6", sku: "JBG-BG-42", size: "42R", stock_quantity: 2, price: 55000, compare_at_price: 65000, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-7",
    name: "Silver Cufflink Set",
    slug: "silver-cufflink-set",
    description:
      "Sterling silver cufflinks with a minimalist square design. Presented in a premium gift box. Weight: 12g each.",
    category_id: "cat-3",
    base_price: 5500,
    compare_at_price: null,
    cost_per_item: 1200,
    fabric: "Sterling Silver",
    fit: "classic",
    color: "Silver",
    is_visible: true,
    is_featured: false,
    created_at: "2024-03-05T00:00:00Z",
    updated_at: "2024-03-05T00:00:00Z",
    deleted_at: null,
    category: categories[2],
    images: [
      {
        id: "img-7-1",
        product_id: "prod-7",
        url: "/pexels-karola-g-7876289.jpg",
        thumbnail_url: "/pexels-karola-g-7876289.jpg",
        medium_url: "/pexels-karola-g-7876289.jpg",
        alt: "Silver cufflink set",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-7-1", product_id: "prod-7", sku: "CF-SV-STD", size: "Standard", stock_quantity: 30, price: 5500, compare_at_price: null, is_out_of_stock: false },
    ],
  },
  {
    id: "prod-8",
    name: "Leather Belt - Classic Black",
    slug: "leather-belt-classic-black",
    description:
      "Full-grain leather dress belt with a brushed silver buckle. Width: 3.5cm. Made in Italy.",
    category_id: "cat-3",
    base_price: 4500,
    compare_at_price: 5500,
    cost_per_item: 900,
    fabric: "Full-Grain Leather",
    fit: "classic",
    color: "Black",
    is_visible: true,
    is_featured: false,
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-03-10T00:00:00Z",
    deleted_at: null,
    category: categories[2],
    images: [
      {
        id: "img-8-1",
        product_id: "prod-8",
        url: "/pexels-karola-g-7876289.jpg",
        thumbnail_url: "/pexels-karola-g-7876289.jpg",
        medium_url: "/pexels-karola-g-7876289.jpg",
        alt: "Black leather belt",
        position: 0,
        is_primary: true,
      },
    ],
    variants: [
      { id: "var-8-1", product_id: "prod-8", sku: "BLT-BK-32", size: "32", stock_quantity: 12, price: 4500, compare_at_price: 5500, is_out_of_stock: false },
      { id: "var-8-2", product_id: "prod-8", sku: "BLT-BK-34", size: "34", stock_quantity: 15, price: 4500, compare_at_price: 5500, is_out_of_stock: false },
      { id: "var-8-3", product_id: "prod-8", sku: "BLT-BK-36", size: "36", stock_quantity: 10, price: 4500, compare_at_price: 5500, is_out_of_stock: false },
    ],
  },
];
